export const APP_CONFIG = {
  NAME: 'Rakhshan Chat',
  BUNDLE_ID: 'com.rakhshan.chat',
  VERSION: '1.0.0',
} as const;

export const LIMITS = {
  MESSAGE_MAX_LENGTH: 4096,
  GROUP_MAX_MEMBERS: 200,
  CHANNEL_MAX_MEMBERS: 100_000,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 32,
  DISPLAY_NAME_MIN_LENGTH: 1,
  DISPLAY_NAME_MAX_LENGTH: 64,
  BIO_MAX_LENGTH: 256,
  CHAT_NAME_MAX_LENGTH: 128,
  CHAT_DESCRIPTION_MAX_LENGTH: 512,
  FILE_MAX_SIZE_MB: 100,
  IMAGE_MAX_SIZE_MB: 20,
  VIDEO_MAX_SIZE_MB: 100,
  VOICE_NOTE_MAX_DURATION_SECONDS: 300,
  OTP_LENGTH: 6,
  OTP_EXPIRY_SECONDS: 120,
  MAX_PINNED_CHATS: 5,
  MAX_DEVICES_PER_USER: 5,
  MESSAGES_PER_PAGE: 50,
  CHATS_PER_PAGE: 20,
  SEARCH_RESULTS_PER_PAGE: 20,
} as const;

export const TIMEOUTS = {
  WS_HEARTBEAT_INTERVAL_MS: 30_000,
  WS_RECONNECT_BASE_DELAY_MS: 1_000,
  WS_RECONNECT_MAX_DELAY_MS: 30_000,
  WS_CONNECTION_TIMEOUT_MS: 10_000,
  TYPING_INDICATOR_TIMEOUT_MS: 5_000,
  TYPING_DEBOUNCE_MS: 500,
  API_REQUEST_TIMEOUT_MS: 30_000,
  MESSAGE_SEND_TIMEOUT_MS: 15_000,
  CALL_RING_TIMEOUT_MS: 45_000,
  OFFLINE_SYNC_INTERVAL_MS: 60_000,
} as const;

export const MEDIA_TYPES = {
  IMAGE: ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/heic'],
  VIDEO: ['video/mp4', 'video/quicktime', 'video/webm'],
  AUDIO: ['audio/mpeg', 'audio/mp4', 'audio/ogg', 'audio/wav', 'audio/aac'],
  DOCUMENT: [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/plain',
    'application/zip',
  ],
} as const;

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CODE: 'AUTH_INVALID_CODE',
  AUTH_CODE_EXPIRED: 'AUTH_CODE_EXPIRED',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_DEVICE_LIMIT: 'AUTH_DEVICE_LIMIT',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_BLOCKED: 'USER_BLOCKED',
  USERNAME_TAKEN: 'USERNAME_TAKEN',

  // Chat
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  CHAT_ACCESS_DENIED: 'CHAT_ACCESS_DENIED',
  CHAT_MEMBER_LIMIT: 'CHAT_MEMBER_LIMIT',

  // Message
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',

  // Call
  CALL_NOT_FOUND: 'CALL_NOT_FOUND',
  CALL_ALREADY_ACTIVE: 'CALL_ALREADY_ACTIVE',
  CALL_USER_BUSY: 'CALL_USER_BUSY',

  // Media
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  MEDIA_INVALID_TYPE: 'MEDIA_INVALID_TYPE',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',

  // Encryption
  ENCRYPTION_KEY_MISMATCH: 'ENCRYPTION_KEY_MISMATCH',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;

export const WS_CLOSE_CODES = {
  NORMAL: 1000,
  GOING_AWAY: 1001,
  PROTOCOL_ERROR: 1002,
  AUTH_FAILED: 4001,
  TOKEN_EXPIRED: 4002,
  RATE_LIMITED: 4003,
  SERVER_ERROR: 4500,
} as const;

export const ENCRYPTION = {
  KEY_ALGORITHM: 'x25519',
  CIPHER_ALGORITHM: 'xsalsa20-poly1305',
  MEDIA_CIPHER: 'aes-256-gcm',
  KEY_SIZE: 32,
  NONCE_SIZE: 24,
  IV_SIZE: 12,
  PRE_KEY_COUNT: 100,
} as const;
